output "file_id" {
  description = "Unique ID generated by the local_file resource."
  value       = local_file.config.id
}

output "file_path" {
  description = "Path of the file created by this module instance."
  value       = local_file.config.filename
}
